apiVersion: v2
appVersion: v1.2.0
name: synology-csi
description: A Helm chart for the Synology CSI Driver
keywords:
  - Synology
  - CSI Driver
kubeVersion: ">= 1.20.0"
sources:
  - https://github.com/sob/synology-csi-talos/tree/main
  - https://github.com/zebernst/synology-csi-talos/tree/main
  - https://github.com/SynologyOpenSource/synology-csi/tree/main
version: 0.9.5-pre.1
